### ISSUE TITLE
Sample_Data

### ISSUE THREAD

**Issue by Mujingrui** [DataverseLabs/pyinterpolate#118]
**Package version**
0.2.2.post2
**Describe the bug**
When I open the file (.shp) in sample_data/breast_cancer & sample_data/population_blocks and read it as geopandas.dataframe, there are no crs objects (areal.crs == None). 
And there is an error after running "points_in_area = get_points_within_area(areal_data, point_data, areal_id_col_name=areal_id, points_val_col_name=points_val)"
CRSError: Invalid projection: : (Internal Proj Error: proj_create: unrecognized format / unknown name)

**To Reproduce**
points_in_area = get_points_within_area(areal_data, point_data, areal_id_col_name=areal_id,
                                        points_val_col_name=points_val)

**Input Data Schema**

**Expected behavior**

**Screenshots**
<img width="390" alt="bug" src="https://user-images.githubusercontent.com/50231196/114930570-281cd200-9e03-11eb-91fa-acca414eee56.PNG">

**Desktop (please complete the following information):**
 -LINUX (Windows Subsystem Linux System)

**Additional context**

**Comment by szymon-datalions** [comment]
Hi @Mujingrui ,

It is a strange behavior. I've checked both files in the main branch and their CRS is:

```
<Geographic 2D CRS: EPSG:4269>
Name: NAD83
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: North America - NAD83
- bounds: (167.65, 14.92, -47.74, 86.46)
Datum: North American Datum 1983
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich
```
Could you check how it works if you use data and tutorial from the `dev` branch? [Link to the tutorial](https://github.com/szymon-datalions/pyinterpolate/blob/dev/tutorials/Semivariogram%20Regularization%20(Intermediate).ipynb)

One other thing: before I start to think about system (or VM) depended issues - could you look into those shapefiles in QGIS or other software? Are you able to read their crs / projection outside your VM?

**Comment by Mujingrui** [comment]
Hi, @szymon-datalions
Thank you for your reply.
I checked it again and the CRS object is still None when I used rgdal pcakage in R to open the .shp file. I reassigned EPSG: 4269 to it in R and saved a new shp file. Then opened the new file in Python3, it can work. the CRS object is not NONE.

**Comment by szymon-datalions** [comment]
Hi @Mujingrui ,

Thank you for your replay and a time for data-check. I will take a closer look into data sources in each possible channel of distribution and check if CRS is damaged or present. Then I'll close this issue.

**Comment by SimonMolinsky** [comment]
Now both datasets have `ESRI:102004 - USA_Contiguous_Lambert_Conformal_Conic` projection, so I can close the issue. Those were tested multiple times when paper with package was written.
