### ISSUE TITLE
Module distance: calc_point_to_point() distance

### ISSUE THREAD

**Issue by SimonMolinsky** [DataverseLabs/pyinterpolate#151]

**Comment by SimonMolinsky** [comment]
@ethmtrgt are you working on this issue? I'd like to move with it (it is a very important step of the logic behind the package) but for now, I can use the older function for my purposes :) Maybe something is not clear in my response to you? I can explain it further :)

**Comment by ethmtrgt** [comment]
Oh, I can't believe I saw your reply 2 weeks later... I probably missed it in my notifications. I am sorry if I blocked the flow :(

**Comment by SimonMolinsky** [comment]
No, no, everything is fine! I just want to know if you're still into it? :)
