### ISSUE TITLE
Module transform: refactorization

### ISSUE THREAD

**Issue by SimonMolinsky** [DataverseLabs/pyinterpolate#165]
This part of the code may be significantly affected by changes in the data structures, so there is space for improvements

- [x] get_points_within_area
- [x] prepare_areal_shapefile
- [x] get_areal_centroids (?)
- [x] prepare_kriging_data
- [x] prepare_poisson_kriging_data
- [x] prepare_ata_data
- [x] prepare_ata_known_areas
- [x] prepare_distances_list_unknown_area
- [x] prepare_atp_data
- [x] check_points_within_ellipse
- [x] select_values_in_range
- [x] get_total_value_of_area
- [x] set_areal_weights
- [x] does_variogram_exist

**Comment by Khushi369** [comment]
Hi, I want to contribute.
Could you please assign me this issue?

**Comment by SimonMolinsky** [comment]
Hi @Khushi369 ,

Thank you for your interest! To make it easier for you, here're some tips:

- core branch for those improvements is `v0.3`,
- core branch with the most stable code is `dev` - it is the place, from where functions should be taken at first,
- try to write unit tests for each function (or, just rewrite existing unit tests),
- use docstrings, how: https://github.com/DataverseLabs/pyinterpolate/wiki/Docstrings
- if you need any help, please let me know :)
- if you see a place for improvement, especially for code to run faster, then don't ask and change it.


Once more, thank you for your help!
