### ISSUE TITLE
[Enhancement] Add __repr__ method to the most important classes

### ISSUE THREAD

**Issue by SimonMolinsky** [DataverseLabs/pyinterpolate#175]
**Is your feature request related to a problem? Please describe.**
The package classes don't have a `__repr__()` method with an example run of specific methods. It will be nice to update the code with it.

**Describe the solution you'd like**
Each class with the `__repr__()` method, especially `TheoreticalSemivariogram()` and `Krige()` classes.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by NarayanAdithya** [comment]
I could work on this, but I would need an idea of what each function has to return in the `__repr__()` method.

**Comment by szymon-datalions** [comment]
Hi! Thanks for the interest! I'm grateful for it :)

Here is detailed info:

[`TheoreticalSemivariogram` class](https://github.com/DataverseLabs/pyinterpolate/blob/main/pyinterpolate/semivariance/semivariogram_fit/fit_semivariance.py)

__repr__ should return:
a) all the params if `self.chosen_model_name` & `self.nugget` & `self.range` & `self.sill` are not None (all of them) -> there is a chance that this class was initialized with `import_model()` method and in this case it doesn't have other parameters but it doesn't matter.
b) only `empirical_semivariance`, `points_array` and `verbose` if all params from a) are not set.

It shouldn't be a human-readable format but a copy of an object's instance.

---

[`Krige` class](https://github.com/DataverseLabs/pyinterpolate/blob/main/pyinterpolate/kriging/point_kriging/kriging.py)

__repr__ should return: firstly, the `TheoreticalSemivariogram` instance used to initialize `Krige` and then the array of known points passed into the model. This class checks if `TheoreticalSemivariogram` is present and if it's fitted (so only scenario a) from the first example should work with this __repr__ (?)).

**Comment by NarayanAdithya** [comment]
Okay, So do you want me to use if-else ladder to check which attributes are None and not display them in the `__repr__` or can I just return None, eg:
```
class A():
    def __init__(self,a=None,b=None):
        self.a=a
        self.b=b
    def __repr__():
        return str((self.a,self.b))
```


If this is what you wanted feel free to assign me this task.

**Comment by szymon-datalions** [comment]
You can return `None`. Thanks, I'm assigning you to the task.

**Comment by szymon-datalions** [comment]
Hmmm... I think that `?` or `()` symbols in path here: `'docs/build/doctrees/nbsphinx/tutorials/How good is my model? Compare Kriging results to the IDW model (Basic).ipynb'` are causing this problem. What is your operating system?

I'll add whole `docs/build/*` path to `.gitignore` and we will see what'll happen.

**Comment by NarayanAdithya** [comment]
Okay, I am checking now

**Comment by szymon-datalions** [comment]
Just in case: https://stackoverflow.com/questions/36827671/git-clone-displaying-errors-and-marking-files-as-deleted-in-windows-10

**Comment by NarayanAdithya** [comment]
Thanks a lot @szymon-datalions , I have WSL setup , I will switch to that
