### ISSUE TITLE
[TypeError] TypeError: loop of ufunc does not support argument 0 of type float which has no callable sqrt method

### ISSUE THREAD

**Issue by SimonMolinsky** [DataverseLabs/pyinterpolate#306]
Produced by line:

https://github.com/DataverseLabs/pyinterpolate/blob/02289ae0967bd7fc4c28df10071afe1c0bae5733/pyinterpolate/distance/distance.py#L214

Problem:

- `numpy` throws `TypeError` when data of type `int` is passed into a function

Solution:

- set `casting` to `unsafe` (or `dtype` to `float`).

**Comment by Lakshayainani** [comment]
Will be working on this one.

**Comment by SimonMolinsky** [comment]
@Lakshayainani I've assigned you to this issue, here are docs that may be interesting: 

- https://numpy.org/doc/stable/reference/generated/numpy.sqrt.html
- https://numpy.org/doc/stable/reference/ufuncs.html#ufuncs-kwargs (casting, dtype)

**Comment by SimonMolinsky** [comment]
Please, push PR later on to the `dev` branch :)

**Comment by Lakshayainani** [comment]
> Please, push PR later on to the `dev` branch :)

Done.

**Comment by SimonMolinsky** [comment]
Thanks! I'll close the issue now :)

**Comment by SimonMolinsky** [comment]
@Lakshayainani , one more thing:

I plan to update the package, but to do so, I need to ask if you want to be included in the contributors file here: https://github.com/DataverseLabs/pyinterpolate/blob/main/docs/source/community/doc_parts/contributors.rst ?

If yes, please let me know ASAP :) And give me **your name**, because pattern is:

NAME OF THE CONTRIBUTOR : Github Handle of the contributor

**Comment by Lakshayainani** [comment]
> 

Sure please add me 
Lakshaya Inani : Lakshayainani
