### ISSUE TITLE
Stable documentation points to 0.4 instead of 0.5

### ISSUE THREAD

**Issue by martinfleis** [DataverseLabs/pyinterpolate#414]
Hi, I noticed that the `stable` documentation on https://pyinterpolate.readthedocs.io/en/stable/ shows documentation for 0.4, even though the latest stable release is 0.5. As there are some API differences, it took me a while to figure out what is wrong 😅. I suppose that RTD stable build needs an update to pick up changes.

**Comment by SimonMolinsky** [comment]
@martinfleis Thank you again, problem fixed :) Somehow I missed the changes of RTD configuration in September.
