### ISSUE TITLE
need for pylibtiff==0.5.1 pin?

### ISSUE THREAD

**Issue by martinfleis** [DataverseLabs/pyinterpolate#422]
Hey,

We have just released geopandas 1.0 and I've noticed that pyinterpolate is 0.5 cannot be installed alongside geopandas 1.0 due to your pin `pylibtiff==0.5.1` . GeoPandas now requires fairly recent pyogrio which depends on pylibtiff via GDAL and is built only against newer version. 

Is there a need to have such a strict pin? Any chance of relaxing it, or at least bumping to 0.6.1?

Thanks!

**Comment by martinfleis** [comment]
One more observation. Pinning geopandas to 1.0 resolves an environment with pyinterpolate 0.4, which probably did not have such restriction. Given the changes in API between 0.4. and 0.5 and unavailability of docs for 0.4 on readthedocs, this can be fairly confusing for users. Happy to assist resolving issues if there are some preventing you from removing the pin.

**Comment by SimonMolinsky** [comment]
Hi @martinfleis 

Thanks for posting this issue! I'll check and resolve it in the next hour or so. 

Tomorrow, I have `GeoPandas` workshops for QGIS users in Poland. Good to hear about 1.0 version of the package :)

**Comment by SimonMolinsky** [comment]
Okay, it won't be so easy. I need to change some things with `GeoPandas >= 1.0.0` (some tests fail), but I'm working on it.

**Comment by martinfleis** [comment]
Let me know if you need any help.
