### ISSUE TITLE
Interpolate raster - function for storing georeferenced images is needed

### ISSUE THREAD

**Issue by SimonMolinsky** [DataverseLabs/pyinterpolate#76]
At this point array interpolation ```interpolate_raster``` function output is:

```python
[[numpy array of interpolated values, numpy array of interpolation errors], [pixel size, min x, max x, min y, max y]]
```

It'd be nice to have function which saves this array to some georeferenced image, as example, to jpg + jgw pairs (without additional external packages needed to be installed).

**Comment by szymon-datalions** [comment]
Ok, function is the next candidate for development after the multiprocessing enhancement and Python 3.8+ compatibility development. If you know something about the raster processing in Python then don't wait and please, help community :)
